[package]
name = "rust-prost-gen"
version = "0.2.2"
authors = ["Dwayne Bradley <dwayne.bradley@gmail.com>"]
edition = "2021"

[dependencies]
bytes = "1.1.0"
prost = "0.9.0"
prost-types = "0.9.0"
prost-build = { version = "0.9.0" }

