[package]
name = "rust-prost-gen"
version = "0.1.0"
authors = ["Dwayne Bradley <dwayne.bradley@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.5.4"
prost = "0.6.1"
prost-types = "0.6.1"
prost-build = { version = "0.6.1" }

