[package]
name = "rust-prost-gen"
version = "0.2.0"
authors = ["Dwayne Bradley <dwayne.bradley@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "1.0.0"
prost = "0.7.0"
prost-types = "0.7.0"
prost-build = { version = "0.7.0" }

